import type { SwiperCard } from '../types';

export const people: SwiperCard[] = [
  {
    id: '1',
    firstName: 'Ali',
    lastName: 'Madad',
    job: 'Software Developer',
    photo: require('../assets/images/ali-madad.jpg'),
    age: 27,
    gender: 'male',
  },
  {
    id: '2',
    firstName: 'Ali',
    lastName: 'Pazani',
    job: 'Dancer',
    photo: require('../assets/images/ali-pazani.jpg'),
    age: 25,
    gender: 'female',
  },
  {
    id: '3',
    firstName: 'Anna',
    lastName: 'Tarazevich',
    job: 'Massage Therapist',
    photo: require('../assets/images/anna-tarazevich.jpg'),
    age: 25,
    gender: 'female',
  },
  {
    id: '4',
    firstName: 'Hill',
    lastName: 'Creation',
    job: 'Psychologist',
    photo: require('../assets/images/creation-hill.jpg'),
    age: 26,
    gender: 'male',
  },
  {
    id: '5',
    firstName: 'Ichad',
    lastName: 'Windiagiri',
    job: 'Bookkeeping clerk',
    photo: require('../assets/images/ichad-windhiagiri.jpg'),
    age: 22,
    gender: 'female',
  },
  {
    id: '6',
    firstName: 'Ike',
    lastName: 'Louie',
    job: 'Musician',
    photo: require('../assets/images/ike-louie.jpg'),
    age: 24,
    gender: 'female',
  },
  {
    id: '7',
    firstName: 'Italo',
    lastName: 'Melo',
    job: 'Architect',
    photo: require('../assets/images/italo-melo.jpg'),
    age: 29,
    gender: 'male',
  },
  {
    id: '8',
    firstName: 'Jeffrey',
    lastName: 'Reed',
    job: 'Firefighter',
    photo: require('../assets/images/jeffrey-reed.jpg'),
    age: 28,
    gender: 'male',
  },
  {
    id: '9',
    firstName: 'Misael',
    lastName: 'Garcia',
    job: 'Librarian',
    photo: require('../assets/images/misael-garcia.jpg'),
    age: 26,
    gender: 'female',
  },
  {
    id: '10',
    firstName: 'Sadi',
    lastName: 'Paela',
    job: 'Medical Assistant',
    photo: require('../assets/images/sadi-paela.jpg'),
    age: 23,
    gender: 'female',
  },
  {
    id: '11',
    firstName: 'Sebastiaan',
    lastName: 'Stam',
    job: 'Statistician',
    photo: require('../assets/images/sebastiaan-stam.jpg'),
    age: 32,
    gender: 'male',
  },
  {
    id: '12',
    firstName: 'Simon',
    lastName: 'Robben',
    job: 'Hairdresser',
    photo: require('../assets/images/simon-robben.jpg'),
    age: 34,
    gender: 'male',
  },
  {
    id: '13',
    firstName: 'Spencer',
    lastName: 'Selover',
    job: 'Court Reporter',
    photo: require('../assets/images/spencer-selover.jpg'),
    age: 37,
    gender: 'male',
  },
  {
    id: '14',
    firstName: 'Spring',
    lastName: 'Loan',
    job: 'Registered Nurse',
    photo: require('../assets/images/spring-loan.jpg'),
    age: 27,
    gender: 'female',
  },
];
